### ISSUE TITLE
Trying to tweak the theme a little

### ISSUE THREAD

**Issue by enzime4u** [Jimmydalecleveland/vscode-everset-theme#3]
Hi , your theme is great for Rect / Javascript , really good on the eyes and great readability !
I have difficulties on making the import as an italic .

I managed to make the variable declaration, function declaration italic , the return keyword NOT-italic ! But I couldn't do it with the import keyword to appear in italics. Can you give me a hint ? 
Thank you

**Comment by laurakcleve** [comment]
In the italic version of the theme the import keyword is already in italics as far as I can see.
![Capture](https://user-images.githubusercontent.com/3967484/56970431-545ebb80-6b24-11e9-8174-2ed8b9fc194d.PNG)
Is this what you mean?

**Comment by enzime4u** [comment]
super-thank you !!!!
